# yaml-language-server: $schema=https://hugoalh.github.io/schema/json/github-labels.json
- name: "Platform/AlpineLinux"
  color: "#0D597F"
  description: "Related to Alpine Linux."
  aliases:
    - "* Alpine"
    - "* AlpineLinux"
    - "Platform/LinuxAlpine"
- name: "Platform/Android"
  color: "#3DDC84"
  description: "Related to Android."
  aliases:
    - "* Android"
- name: "Platform/ArchLinux"
  color: "#1793D1"
  description: "Related to Arch Linux."
  aliases:
    - "* ArchLinux"
- name: "Platform/Bluesky"
  color: "#0285FF"
  description: "Related to Bluesky."
  aliases:
    - "* Bluesky"
- name: "Platform/Bun"
  color: "#F9F1E1"
  description: "Related to Bun."
  aliases:
    - "* Bun"
- name: "Platform/CentOS"
  color: "#262577"
  description: "Related to CentOS."
  aliases:
    - "* CentOS"
- name: "Platform/ClamAV"
  color: "#B83033"
  description: "Related to ClamAV."
  aliases:
    - "* ClamAV"
- name: "Platform/CloudflareWorkers"
  color: "#F38020"
  description: "Related to Cloudflare Workers."
  aliases:
    - "* CloudflareWorkers"
- name: "Platform/Codeberg"
  color: "#2185D0"
  description: "Related to Codeberg."
  aliases:
    - "* Codeberg"
- name: "Platform/CodeQL"
  color: "#FFFFFF"
  description: "Related to CodeQL."
  aliases:
    - "* CodeQL"
- name: "Platform/Crowdin"
  color: "#2E3340"
  description: "Related to Crowdin."
  aliases:
    - "* Crowdin"
- name: "Platform/CurseForge"
  color: "#F16436"
  description: "Related to CurseForge."
  aliases:
    - "* CurseForge"
- name: "Platform/Dart"
  color: "#0175C2"
  description: "Related to Dart."
  aliases:
    - "* Dart"
- name: "Platform/Debian"
  color: "#A81D33"
  description: "Related to Debian."
  aliases:
    - "* Debian"
    - "Platform/LinuxDebian"
- name: "Platform/Deno"
  color: "#000000"
  description: "Related to Deno."
  aliases:
    - "* Deno"
- name: "Platform/DenoNetwork"
  color: "#000000"
  description: "Related to Deno Deploy, Deno Land, or Deno Module Registry."
  aliases:
    - "* DenoNetwork"
- name: "Platform/Dependabot"
  color: "#025E8C"
  description: "Related to Dependabot."
  aliases:
    - "* Dependabot"
- name: "Platform/Discord"
  color: "#5865F2"
  description: "Related to Discord."
  aliases:
    - "* Discord"
- name: "Platform/Docker"
  color: "#2496ED"
  description: "Related to Docker."
  aliases:
    - "* Docker"
- name: "Platform/DotNet"
  color: "#512BD4"
  description: "Related to .NET."
  aliases:
    - "* DotNet"
- name: "Platform/FDroid"
  color: "#1976D2"
  description: "Related to F-Droid."
  aliases:
    - "* FDroid"
- name: "Platform/FedoraLinux"
  color: "#51A2DA"
  description: "Related to Fedora Linux."
  aliases:
    - "* FedoraLinux"
- name: "Platform/Flutter"
  color: "#02569B"
  description: "Related to Flutter."
  aliases:
    - "* Flutter"
- name: "Platform/Forgejo"
  color: "#FB923C"
  description: "Related to Forgejo."
  aliases:
    - "* Forgejo"
- name: "Platform/Git"
  color: "#F05032"
  description: "Related to Git."
  aliases:
    - "* Git"
- name: "Platform/GitHub"
  color: "#181717"
  description: "Related to GitHub."
  aliases:
    - "* GitHub"
- name: "Platform/GitHubActions"
  color: "#2088FF"
  description: "Related to GitHub Actions."
  aliases:
    - "* GitHubActions"
- name: "Platform/GitHubPackages"
  color: "#181717"
  description: "Related to GitHub Packages."
  aliases:
    - "* GitHubPackages"
- name: "Platform/GitHubPages"
  color: "#222222"
  description: "Related to GitHub Pages."
  aliases:
    - "* GitHubPages"
- name: "Platform/GitLFS"
  color: "#F64935"
  description: "Related to Git LFS."
  aliases:
    - "* GitLFS"
- name: "Platform/Godot"
  color: "#478CBF"
  description: "Related to Godot."
  aliases:
    - "* Godot"
- name: "Platform/Google"
  color: "#4285F4"
  description: "Related to Google."
  aliases:
    - "* Google"
- name: "Platform/GoogleChrome"
  color: "#4285F4"
  description: "Related to Google Chrome."
  aliases:
    - "* GoogleChrome"
- name: "Platform/GooglePlay"
  color: "#414141"
  description: "Related to Google Play."
  aliases:
    - "* GooglePlay"
- name: "Platform/Guilded"
  color: "#F5C400"
  description: "Related to Guilded."
  aliases:
    - "* Guilded"
- name: "Platform/JavaScript"
  color: "#F7DF1E"
  description: "Related to JavaScript."
  aliases:
    - "* JavaScript"
- name: "Platform/JSR"
  color: "#F7DF1E"
  description: "Related to JSR (JavaScript Registry)."
  aliases:
    - "* JSR"
- name: "Platform/Kubernetes"
  color: "#326CE5"
  description: "Related to Kubernetes."
  aliases:
    - "* Kubernetes"
- name: "Platform/Linux"
  color: "#FCC624"
  description: "Related to Linux."
  aliases:
    - "* Linux"
- name: "Platform/MacOS"
  color: "#000000"
  description: "Related to MacOS."
  aliases:
    - "* MacOS"
    - "Platform/AppleOS"
- name: "Platform/Mastodon"
  color: "#6364FF"
  description: "Related to Mastodon."
  aliases:
    - "* Mastodon"
- name: "Platform/MicrosoftAzure"
  color: "#0078D4"
  description: "Related to Microsoft Azure."
  aliases:
    - "* MicrosoftAzure"
- name: "Platform/MicrosoftEdge"
  color: "#0078D7"
  description: "Related to Microsoft Edge."
  aliases:
    - "* MicrosoftEdge"
- name: "Platform/Minecraft"
  color: "#62B47A"
  description: "Related to Minecraft (Bedrock)."
  aliases:
    - "* Minecraft"
- name: "Platform/MinecraftJava"
  color: "#62B47A"
  description: "Related to Minecraft Java."
  aliases:
    - "* MinecraftJava"
- name: "Platform/NodeJS"
  color: "#339933"
  description: "Related to NodeJS."
  aliases:
    - "* NodeJS"
- name: "Platform/NPM"
  color: "#CB3837"
  description: "Related to NPM."
  aliases:
    - "* NPM"
- name: "Platform/Podman"
  color: "#892CA0"
  description: "Related to Podman."
  aliases:
    - "* Podman"
- name: "Platform/PowerShell"
  color: "#5391FE"
  description: "Related to PowerShell."
  aliases:
    - "* PowerShell"
- name: "Platform/PowerShellGallery"
  color: "#5391FE"
  description: "Related to PowerShell Gallery."
  aliases:
    - "* PowerShellGallery"
- name: "Platform/Python"
  color: "#3776AB"
  description: "Related to Python."
  aliases:
    - "* Python"
- name: "Platform/RevoltChat"
  color: "#FF4655"
  description: "Related to Revolt Chat."
  aliases:
    - "* RevoltChat"
- name: "Platform/Roblox"
  color: "#000000"
  description: "Related to Roblox."
  aliases:
    - "* Roblox"
- name: "Platform/RobloxStudio"
  color: "#00A2FF"
  description: "Related to Roblox Studio."
  aliases:
    - "* RobloxStudio"
- name: "Platform/Rust"
  color: "#000000"
  description: "Related to Rust."
  aliases:
    - "* Rust"
- name: "Platform/Steam"
  color: "#000000"
  description: "Related to Steam."
  aliases:
    - "* Steam"
- name: "Platform/Telegram"
  color: "#26A5E4"
  description: "Related to Telegram."
  aliases:
    - "* Telegram"
- name: "Platform/TypeScript"
  color: "#3178C6"
  description: "Related to TypeScript."
  aliases:
    - "* TypeScript"
- name: "Platform/Ubuntu"
  color: "#E95420"
  description: "Related to Ubuntu."
  aliases:
    - "* Ubuntu"
    - "Platform/LinuxUbuntu"
- name: "Platform/VisualStudio"
  color: "#5C2D91"
  description: "Related to Visual Studio."
  aliases:
    - "* VisualStudio"
- name: "Platform/VisualStudioCode"
  color: "#007ACC"
  description: "Related to Visual Studio Code."
  aliases:
    - "* VisualStudioCode"
- name: "Platform/VisualStudioMarketplace"
  color: "#CB2E6D"
  description: "Related to Visual Studio Marketplace."
  aliases:
    - "* VisualStudioMarketplace"
- name: "Platform/Weblate"
  color: "#2ECCAA"
  description: "Related to Weblate."
  aliases:
    - "* Weblate"
- name: "Platform/Windows"
  color: "#0078D4"
  description: "Related to Windows."
  aliases:
    - "* Windows"
- name: "Platform/YARA"
  color: "#808080"
  description: "Related to YARA."
  aliases:
    - "* YARA"
- name: "Priority/High 🔴"
  color: "#F44336"
  description: "This is high priority."
  aliases:
    - "🔴 High"
- name: "Priority/Low 🟢"
  color: "#4CAF50"
  description: "This is low priority."
  aliases:
    - "🟢 Low"
- name: "Priority/Medium 🟡"
  color: "#FFEB3B"
  description: "This is medium priority."
  aliases:
    - "🟡 Medium"
- name: "Priority/Urgent 🚨"
  color: "#D50000"
  description: "This is urgent."
  aliases:
    - "🚨 Urgent"
    - "Priority/Critical 🚨"
- name: "Status/Duplicated 🔁"
  color: "#CFD3D7" # GitHub Default Label Color
  description: "This already exists."
  aliases:
    - "duplicate" # GitHub Default Label
    - "🔁 Duplicated"
- name: "Status/HelpWanted ⛑️"
  color: "#008672" # GitHub Default Label Color
  description: "This needs extra help."
  aliases:
    - "help wanted" # GitHub Default Label
    - "⛑️ HelpWanted"
- name: "Status/Invalid ⚠️"
  color: "#E4E669" # GitHub Default Label Color
  description: "This does not seem right."
  aliases:
    - "invalid" # GitHub Default Label
    - "⚠️ Invalid"
- name: "Status/Investigating 🔍"
  color: "#03A9F4"
  description: "This is in investigating."
  aliases:
    - "🔍 Investigating"
- name: "Status/NoSolution 🤷"
  color: "#FFFFFF"
  description: "This cannot be worked on due to no possible solution."
  aliases:
    - "🤷 NoSolution"
- name: "Status/Question ❓"
  color: "#D876E3" # GitHub Default Label Color
  description: "This needs further information."
  aliases:
    - "question" # GitHub Default Label
    - "❓ Question"
- name: "Status/Transfer ↗️"
  color: "#607D8B"
  description: "This is transferred to a more relevant place."
  aliases:
    - "↗️ Transfer"
- name: "Status/WillNotFix 🙅"
  color: "#FFFFFF" # GitHub Default Label Color
  description: "This will not be worked on."
  aliases:
    - "wontfix" # GitHub Default Label
    - "🙅 WillNotFix"
- name: "Type/Bug 🐛"
  color: "#D73A4A" # GitHub Default Label Color
  description: "Something is not working as expected or intended."
  aliases:
    - "bug" # GitHub Default Label
    - "🐛 Bug"
- name: "Type/Chore ⚙️"
  color: "#C0C0C0"
  description: "Miscellaneous task."
  aliases:
    - "⚙️ Chore"
- name: "Type/Dependency 📦"
  color: "#6D4C41"
  description: "Related to dependency."
  aliases:
    - "📦 Dependency"
- name: "Type/Documentation 📓"
  color: "#0075CA" # GitHub Default Label Color
  description: "Additions or improvements to the documentation."
  aliases:
    - "documentation" # GitHub Default Label
    - "📓 Documentation"
- name: "Type/Enhancement 💡"
  color: "#A2EEEF" # GitHub Default Label Color
  description: "New feature or request."
  aliases:
    - "enhancement" # GitHub Default Label
    - "💡 Enhancement"
