- name: "Platform/Android"
  color: "#3DDC84"
  description: "Related to Android."
  aliases:
    - "Platform/Android 🤖"
- name: "Platform/AssemblyScript"
  color: "#007AAC"
  description: "Related to AssemblyScript."
- name: "Platform/Azure"
  color: "#0078D4"
  description: "Related to Azure."
- name: "Platform/ClamAV"
  color: "#B83033"
  description: "Related to ClamAV."
- name: "Platform/CodeFactor"
  color: "#F44A6A"
  description: "Related to CodeFactor."
- name: "Platform/Crowdin"
  color: "#2E3340"
  description: "Related to Crowdin."
- name: "Platform/Deno"
  color: "#000000"
  description: "Related to Deno."
- name: "Platform/DenoDeploy"
  color: "#000000"
  description: "Related to Deno Deploy."
  aliases:
    - "Platform/Deno 🦕"
- name: "Platform/Dependabot"
  color: "#025E8C"
  description: "Related to Dependabot."
- name: "Platform/Discord"
  color: "#5865F2"
  description: "Related to Discord."
- name: "Platform/Docker"
  color: "#2496ED"
  description: "Related to Docker."
  aliases:
    - "Platform/Docker 🐳"
- name: "Platform/DotNet"
  color: "#512BD4"
  description: "Related to .NET."
- name: "Platform/Git"
  color: "#F05032"
  description: "Related to Git."
- name: "Platform/GitLFS"
  color: "#F64935"
  description: "Related to Git LFS."
- name: "Platform/GitHub"
  color: "#181717"
  description: "Related to GitHub."
- name: "Platform/GitHubActions"
  color: "#2088FF"
  description: "Related to GitHub Actions."
  aliases:
    - "Platform/GitHub/Actions"
    - "Platform/GitHub/Actions :octocat:"
- name: "Platform/GitHubPages"
  color: "#222222"
  description: "Related to GitHub Pages."
- name: "Platform/Google"
  color: "#4285F4"
  description: "Related to Google."
- name: "Platform/JavaScript"
  color: "#F7DF1E"
  description: "Related to JavaScript."
- name: "Platform/Kaspersky"
  color: "#006D5C"
  description: "Related to Kaspersky."
- name: "Platform/Linux"
  color: "#FCC624"
  description: "Related to Linux."
  aliases:
    - "Platform/Linux 🐧"
- name: "Platform/LinuxAlpine"
  color: "#0D597F"
  description: "Related to Linux Alpine."
  aliases:
    - "Platform/Linux/Alpine"
    - "Platform/Linux/Alpine 🏔"
- name: "Platform/LinuxDebian"
  color: "#A81D33"
  description: "Related to Linux Debian."
  aliases:
    - "Platform/Linux/Debian"
    - "Platform/Linux/Debian 🌪"
- name: "Platform/LinuxUbuntu"
  color: "#E95420"
  description: "Related to Linux Ubuntu."
- name: "Platform/MacOS"
  color: "#000000"
  description: "Related to MacOS."
  aliases:
    - "Platform/MacOS 🙂"
- name: "Platform/NodeJS"
  color: "#339933"
  description: "Related to NodeJS."
  aliases:
    - "Platform/NodeJS 🔘"
- name: "Platform/NPM"
  color: "#CB3837"
  description: "Related to NPM."
- name: "Platform/Others"
  color: "#ffffff"
  description: "Related to other platforms."
- name: "Platform/PNPM"
  color: "#F69220"
  description: "Related to PNPM."
- name: "Platform/POEditor"
  color: "#00BCC9"
  description: "Related to POEditor."
- name: "Platform/PowerShell"
  color: "#5391FE"
  description: "Related to PowerShell."
  aliases:
    - "Platform/PowerShell 🐚"
- name: "Platform/PowerShellGallery"
  color: "#5391FE"
  description: "Related to PowerShell Gallery."
- name: "Platform/Python"
  color: "#3776AB"
  description: "Related to Python."
  aliases:
    - "Platform/Python 🐍"
- name: "Platform/Replit"
  color: "#F26207"
  description: "Related to Replit."
- name: "Platform/Roblox"
  color: "#000000"
  description: "Related to Roblox."
- name: "Platform/RobloxStudio"
  color: "#00A2FF"
  description: "Related to Roblox Studio."
- name: "Platform/SemVer"
  color: "#3F4551"
  description: "Related to SemVer."
- name: "Platform/TypeScript"
  color: "#3178C6"
  description: "Related to TypeScript."
- name: "Platform/VisualStudio"
  color: "#5C2D91"
  description: "Related to Visual Studio."
- name: "Platform/VisualStudioCode"
  color: "#007ACC"
  description: "Related to Visual Studio Code."
- name: "Platform/Windows"
  color: "#0078D4"
  description: "Related to Windows."
  aliases:
    - "Platform/Windows 🪟"
- name: "Platform/Yarn"
  color: "#2C8EBB"
  description: "Related to Yarn."
- name: "Priority/Critical 🚨"
  color: "#b60205"
  description: "Critical priority."
- name: "Priority/High 🔴"
  color: "#e81224"
  description: "High priority."
- name: "Priority/Low 🟢"
  color: "#16c60c"
  description: "Low priority."
- name: "Priority/Medium 🟡"
  color: "#fff100"
  description: "Medium priority."
- name: "Status/Duplicated 🔁"
  color: "#c0c0c0"
  description: "This already exists."
- name: "Status/Invalid ⚠️"
  color: "#e4e669"
  description: "This does not seem right."
  aliases:
    - "Status/Invalid ⚠"
- name: "Status/Investigating 🔍"
  color: "#ffc93b"
  description: "This is in investigating."
  aliases:
    - "Status/Investigating 🧐"
- name: "Status/No-Solution 🤷"
  color: "#ffffff"
  description: "This cannot be worked on due to no possible solution."
- name: "Status/Pending 🔵"
  color: "#0078d7"
  description: "This is new."
  aliases:
    - "Status/Unread 🔵"
- name: "Status/Question ❓"
  color: "#d876e3"
  description: "This needs further information."
- name: "Status/Rejected ❌"
  color: "#f03710"
  description: "This is rejected."
- name: "Status/Transfer ↗️"
  color: "#808080"
  description: "This is transferred to the more relevant place."
- name: "Status/WillNotFix 🙅"
  color: "#ffffff"
  description: "This will not be worked on."
  aliases:
    - "Status/Will-Not-Fix 🙅"
- name: "Type/Bug 🐛"
  color: "#d73a4a"
  description: "Something is not working."
- name: "Type/Dependency 📦"
  color: "#bb9167"
  description: "Related to dependency."
- name: "Type/Documentation 📓"
  color: "#5319e7"
  description: "Related to documentation."
  aliases:
    - "Type/Documentation 📚"
- name: "Type/Enhancement ➕"
  color: "#a2eeef"
  description: "New feature or request."
- name: "Type/Help-Wanted ⛑️"
  color: "#008672"
  description: "Need extra attention."
  aliases:
    - "Type/Help-Wanted ⛑"
