# yaml-language-server: $schema=./labels.schema.json
- name: "Platform/Android"
  color: "#3DDC84"
  description: "Related to Android."
- name: "Platform/AssemblyScript"
  color: "#007AAC"
  description: "Related to AssemblyScript."
- name: "Platform/ClamAV"
  color: "#B83033"
  description: "Related to ClamAV."
- name: "Platform/CodeFactor"
  color: "#F44A6A"
  description: "Related to CodeFactor."
- name: "Platform/CodeQL"
  color: "#FFFFFF"
  description: "Related to CodeQL (previous LGTM)."
- name: "Platform/Crowdin"
  color: "#2E3340"
  description: "Related to Crowdin."
- name: "Platform/CurseForge"
  color: "#F16436"
  description: "Related to CurseForge."
- name: "Platform/Deno"
  color: "#000000"
  description: "Related to Deno."
- name: "Platform/DenoNetwork"
  color: "#000000"
  description: "Related to Deno Deploy, Deno KV, or Deno Module Registry."
- name: "Platform/Dependabot"
  color: "#025E8C"
  description: "Related to Dependabot."
- name: "Platform/Discord"
  color: "#5865F2"
  description: "Related to Discord."
- name: "Platform/Docker"
  color: "#2496ED"
  description: "Related to Docker."
- name: "Platform/DotNet"
  color: "#512BD4"
  description: "Related to .NET."
- name: "Platform/Git"
  color: "#F05032"
  description: "Related to Git."
- name: "Platform/GitHub"
  color: "#181717"
  description: "Related to GitHub."
- name: "Platform/GitHubActions"
  color: "#2088FF"
  description: "Related to GitHub Actions."
- name: "Platform/GitHubPackages"
  color: "#181717"
  description: "Related to GitHub Packages."
- name: "Platform/GitHubPages"
  color: "#222222"
  description: "Related to GitHub Pages."
- name: "Platform/GitLFS"
  color: "#F64935"
  description: "Related to Git LFS."
- name: "Platform/Godot"
  color: "#478CBF"
  description: "Related to Godot."
- name: "Platform/GoogleChrome"
  color: "#4285F4"
  description: "Related to Google Chrome."
- name: "Platform/JavaScript"
  color: "#F7DF1E"
  description: "Related to JavaScript."
- name: "Platform/Kaspersky"
  color: "#006D5C"
  description: "Related to Kaspersky."
- name: "Platform/Linux"
  color: "#FCC624"
  description: "Related to Linux."
- name: "Platform/LinuxAlpine"
  color: "#0D597F"
  description: "Related to Linux Alpine."
- name: "Platform/LinuxDebian"
  color: "#A81D33"
  description: "Related to Linux Debian."
- name: "Platform/LinuxUbuntu"
  color: "#E95420"
  description: "Related to Linux Ubuntu."
- name: "Platform/MacOS"
  color: "#000000"
  description: "Related to MacOS."
- name: "Platform/Mastodon"
  color: "#6364FF"
  description: "Related to Mastodon."
- name: "Platform/MicrosoftAzure"
  color: "#0078D4"
  description: "Related to Microsoft Azure."
- name: "Platform/MicrosoftEdge"
  color: "#0078D7"
  description: "Related to Microsoft Edge."
- name: "Platform/Minecraft"
  color: "#62B47A"
  description: "Related to Minecraft (previous Minecraft Bedrock)."
- name: "Platform/MinecraftJava"
  color: "#62B47A"
  description: "Related to Minecraft Java (previous Minecraft)."
- name: "Platform/MongoDB"
  color: "#47A248"
  description: "Related to MongoDB."
- name: "Platform/NodeJS"
  color: "#339933"
  description: "Related to NodeJS."
- name: "Platform/NPM"
  color: "#CB3837"
  description: "Related to NPM."
- name: "Platform/POEditor"
  color: "#00BCC9"
  description: "Related to POEditor."
- name: "Platform/PowerShell"
  color: "#5391FE"
  description: "Related to PowerShell."
- name: "Platform/PowerShellGallery"
  color: "#5391FE"
  description: "Related to PowerShell Gallery."
- name: "Platform/Python"
  color: "#3776AB"
  description: "Related to Python."
- name: "Platform/Replit"
  color: "#F26207"
  description: "Related to Replit."
- name: "Platform/ReplitDatabase"
  color: "#F26207"
  description: "Related to Replit Database."
- name: "Platform/Roblox"
  color: "#000000"
  description: "Related to Roblox."
- name: "Platform/RobloxStudio"
  color: "#00A2FF"
  description: "Related to Roblox Studio."
- name: "Platform/Telegram"
  color: "#26A5E4"
  description: "Related to Telegram."
- name: "Platform/TypeScript"
  color: "#3178C6"
  description: "Related to TypeScript."
- name: "Platform/VisualStudio"
  color: "#5C2D91"
  description: "Related to Visual Studio."
- name: "Platform/VisualStudioCode"
  color: "#007ACC"
  description: "Related to Visual Studio Code."
- name: "Platform/Windows"
  color: "#0078D4"
  description: "Related to Windows."
- name: "Priority/Critical 🚨"
  color: "#D50000"
  description: "Critical priority."
- name: "Priority/High 🔴"
  color: "#F44336"
  description: "High priority."
- name: "Priority/Low 🟢"
  color: "#4CAF50"
  description: "Low priority."
- name: "Priority/Medium 🟡"
  color: "#FFEB3B"
  description: "Medium priority."
- name: "Status/Duplicated 🔁"
  color: "#CFD3D7" # GitHub Default Label Color
  description: "This already exists."
  aliases:
    - "duplicate" # GitHub Default Label
- name: "Status/HelpWanted ⛑️"
  color: "#008672" # GitHub Default Label Color
  description: "This needs extra help."
  aliases:
    - "help wanted" # GitHub Default Label
- name: "Status/Invalid ⚠️"
  color: "#E4E669" # GitHub Default Label Color
  description: "This does not seem right."
  aliases:
    - "invalid" # GitHub Default Label
- name: "Status/Investigating 🔍"
  color: "#03A9F4"
  description: "This is in investigating."
- name: "Status/NoSolution 🤷"
  color: "#FFFFFF"
  description: "This cannot be worked on due to no possible solution."
- name: "Status/Pending 🔵"
  color: "#2196F3"
  description: "This is new."
- name: "Status/Question ❓"
  color: "#D876E3" # GitHub Default Label Color
  description: "This needs further information."
  aliases:
    - "question" # GitHub Default Label
- name: "Status/Rejected ❌"
  color: "#B71C1C"
  description: "This is rejected."
- name: "Status/Transfer ↗️"
  color: "#607D8B"
  description: "This is transferred to a more relevant place."
- name: "Status/WillNotFix 🙅"
  color: "#FFFFFF" # GitHub Default Label Color
  description: "This will not be worked on."
  aliases:
    - "wontfix" # GitHub Default Label
- name: "Type/Bug 🐛"
  color: "#D73A4A" # GitHub Default Label Color
  description: "Something is not working as expected or intended."
  aliases:
    - "bug" # GitHub Default Label
- name: "Type/Dependency 📦"
  color: "#6D4C41"
  description: "Related to dependency."
- name: "Type/Documentation 📓"
  color: "#0075CA" # GitHub Default Label Color
  description: "Additions or improvements to the documentation."
  aliases:
    - "documentation" # GitHub Default Label
- name: "Type/Enhancement 💡"
  color: "#A2EEEF" # GitHub Default Label Color
  description: "New feature or request."
  aliases:
    - "enhancement" # GitHub Default Label
