# yaml-language-server: $schema=https://json.schemastore.org/eslintrc.json
# ESLint v8.55.0 + ESLint Stylistic v1.5.0 + ESLint TypeScript v6.13.0
env:
  browser: true
  node: true
  commonjs: true
  shared-node-browser: true
  es6: true
  es2016: true
  es2017: true
  es2018: true
  es2019: true
  es2020: true
  es2021: true
  es2022: true
  es2023: true
  es2024: true
  worker: true
  amd: true
  mocha: true
  jasmine: true
  jest: true
  phantomjs: true
  protractor: true
  qunit: true
  jquery: true
  prototypejs: true
  shelljs: true
  meteor: true
  mongo: true
  applescript: true
  nashorn: true
  serviceworker: true
  atomtest: true
  embertest: true
  webextensions: true
  greasemonkey: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  allowReserved: false
  ecmaFeatures:
    arrowFunctions: true
    classes: true
    defaultParams: true
    destructuring: true
    experimentalObjectRestSpread: true
    forOf: true
    generators: true
    globalReturn: false
    impliedStrict: true
    jsx: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralDuplicateProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    regexUFlag: true
    regexYFlag: true
    restParams: true
    spread: true
    superInFunctions: false
    templateStrings: true
    unicodeCodePointEscapes: true
plugins:
  - "@stylistic"
  - "@typescript-eslint"
  - "only-warn"
rules:
  array-callback-return:
    - "warn"
    - allowImplicit: true
      checkForEach: true
  no-cond-assign:
    - "warn"
    - "always"
  no-constant-binary-expression:
    - "warn"
  no-constructor-return:
    - "warn"
  no-duplicate-imports:
    - "warn"
  no-new-native-nonconstructor:
    - "warn"
  no-promise-executor-return:
    - "warn"
  no-self-compare:
    - "warn"
  no-unmodified-loop-condition:
    - "warn"
  no-unreachable-loop:
    - "warn"
  no-unused-private-class-members:
    - "warn"
  no-use-before-define:
    - "warn"
  require-atomic-updates:
    - "warn"
  use-isnan:
    - "warn"
    - enforceForSwitchCase: true
      enforceForIndexOf: true
  arrow-body-style:
    - "warn"
    - "always"
  class-methods-use-this:
    - "warn"
  curly:
    - "warn"
    - "all"
  default-case:
    - "warn"
  default-case-last:
    - "warn"
  default-param-last:
    - "warn"
  eqeqeq:
    - "warn"
    - "always"
  func-names:
    - "warn"
    - "as-needed"
  func-style:
    - "warn"
    - "declaration"
    - allowArrowFunctions: true
  grouped-accessor-pairs:
    - "warn"
  guard-for-in:
    - "warn"
  new-cap:
    - "warn"
    - newIsCap: true
      capIsNew: false
      properties: true
  no-array-constructor:
    - "warn"
  no-caller:
    - "warn"
  no-confusing-arrow:
    - "warn"
  no-div-regex:
    - "warn"
  no-else-return:
    - "warn"
  no-empty-function:
    - "warn"
  no-empty-static-block:
    - "warn"
  no-eq-null:
    - "warn"
  no-eval:
    - "warn"
  no-extend-native:
    - "warn"
  no-extra-bind:
    - "warn"
  no-extra-label:
    - "warn"
  no-floating-decimal:
    - "warn"
  no-implicit-coercion:
    - "warn"
  no-invalid-this:
    - "warn"
  no-iterator:
    - "warn"
  no-label-var:
    - "warn"
  no-lone-blocks:
    - "warn"
  no-loop-func:
    - "warn"
  no-mixed-operators:
    - "warn"
  no-multi-assign:
    - "warn"
  no-multi-str:
    - "warn"
  no-negated-condition:
    - "warn"
  no-new:
    - "warn"
  no-new-func:
    - "warn"
  no-new-wrappers:
    - "warn"
  no-object-constructor:
    - "warn"
  no-octal-escape:
    - "warn"
  no-param-reassign:
    - "warn"
  no-proto:
    - "warn"
  no-regex-spaces:
    - "warn"
  no-return-assign:
    - "warn"
    - "always"
  no-script-url:
    - "warn"
  no-sequences:
    - "warn"
  no-shadow:
    - "warn"
  no-unneeded-ternary:
    - "warn"
    - defaultAssignment: true
  no-unused-expressions:
    - "warn"
    - allowShortCircuit: false
      allowTernary: false
      allowTaggedTemplates: true
      enforceForJSX: false
  no-useless-call:
    - "warn"
  no-useless-computed-key:
    - "warn"
  no-useless-concat:
    - "warn"
  no-useless-constructor:
    - "warn"
  no-useless-rename:
    - "warn"
  no-useless-return:
    - "warn"
  no-void:
    - "warn"
  one-var-declaration-per-line:
    - "warn"
    - "always"
  prefer-const:
    - "warn"
  prefer-named-capture-group:
    - "warn"
  prefer-numeric-literals:
    - "warn"
  prefer-object-has-own:
    - "warn"
  prefer-object-spread:
    - "warn"
  prefer-regex-literals:
    - "warn"
    - disallowRedundantWrapping: true
  prefer-rest-params:
    - "warn"
  prefer-spread:
    - "warn"
  prefer-template:
    - "warn"
  radix:
    - "warn"
  require-await:
    - "warn"
  require-unicode-regexp:
    - "warn"
  strict:
    - "warn"
    - "never"
  yoda:
    - "warn"
    - "never"
    - exceptRange: true
  "@stylistic/array-bracket-spacing":
    - "warn"
    - "never"
  "@stylistic/array-element-newline":
    - "warn"
    - "consistent"
  "@stylistic/arrow-parens":
    - "warn"
    - "always"
  "@stylistic/arrow-spacing":
    - "warn"
    - before: true
      after: true
  "@stylistic/block-spacing":
    - "warn"
    - "always"
  "@stylistic/brace-style":
    - "warn"
    - "1tbs"
    - allowSingleLine: false
  "@stylistic/comma-dangle":
    - "warn"
    - "never"
  "@stylistic/comma-spacing":
    - "warn"
    - before: false
      after: true
  "@stylistic/comma-style":
    - "warn"
    - "last"
  "@stylistic/computed-property-spacing":
    - "warn"
    - "never"
    - enforceForClassMembers: true
  "@stylistic/dot-location":
    - "warn"
    - "object"
  "@stylistic/eol-last":
    - "warn"
    - "always"
  "@stylistic/func-call-spacing":
    - "warn"
    - "never"
  "@stylistic/function-call-argument-newline":
    - "warn"
    - "consistent"
  "@stylistic/function-paren-newline":
    - "warn"
    - "multiline-arguments"
  "@stylistic/generator-star-spacing":
    - "warn"
    - before: false
      after: true
  "@stylistic/implicit-arrow-linebreak":
    - "warn"
    - "beside"
  "@stylistic/indent":
    - "warn"
    - "tab"
    - SwitchCase: 1
      VariableDeclarator: 1
      outerIIFEBody: 1
      MemberExpression: 1
      FunctionDeclaration:
        parameters: 1
        body: 1
      FunctionExpression:
        parameters: 1
        body: 1
      StaticBlock:
        body: 1
      CallExpression:
        arguments: 1
      ArrayExpression: 1
      ObjectExpression: 1
      ImportDeclaration: 1
      flatTernaryExpressions: true
      offsetTernaryExpressions: false
      ignoreComments: false
  "@stylistic/jsx-quotes":
    - "warn"
    - "prefer-double"
  "@stylistic/key-spacing":
    - "warn"
    - beforeColon: false
      afterColon: true
      mode: "strict"
  "@stylistic/keyword-spacing":
    - "warn"
    - before: true
      after: true
  "@stylistic/multiline-ternary":
    - "warn"
    - "always-multiline"
  "@stylistic/new-parens":
    - "warn"
    - "always"
  "@stylistic/no-extra-parens":
    - "warn"
    - "all"
    - conditionalAssign: false
      returnAssign: false
      nestedBinaryExpressions: false
      ternaryOperandBinaryExpressions: false
      ignoreJSX: "multi-line"
      enforceForArrowConditionals: false
      enforceForSequenceExpressions: false
      enforceForNewInMemberExpressions: true
      enforceForFunctionPrototypeMethods: true
  "@stylistic/no-multi-spaces":
    - "warn"
  "@stylistic/no-multiple-empty-lines":
    - "warn"
    - max: 1
  "@stylistic/no-tabs":
    - "warn"
    - allowIndentationTabs: true
  "@stylistic/no-trailing-spaces":
    - "warn"
    - skipBlankLines: false
      ignoreComments: false
  "@stylistic/no-whitespace-before-property":
    - "warn"
  "@stylistic/nonblock-statement-body-position":
    - "warn"
    - "beside"
  "@stylistic/object-curly-newline":
    - "warn"
    - multiline: true
      consistent: true
  "@stylistic/object-curly-spacing":
    - "warn"
    - "always"
  "@stylistic/operator-linebreak":
    - "warn"
  "@stylistic/padded-blocks":
    - "warn"
    - "never"
    - allowSingleLineBlocks: false
  "@stylistic/padding-line-between-statements":
    - "warn"
  "@stylistic/quotes":
    - "warn"
    - "double"
    - avoidEscape: false
      allowTemplateLiterals: true
  "@stylistic/rest-spread-spacing":
    - "warn"
    - "never"
  "@stylistic/semi":
    - "warn"
    - "always"
    - omitLastInOneLineBlock: false
      omitLastInOneLineClassBody: false
  "@stylistic/semi-spacing":
    - "warn"
    - before: false
      after: true
  "@stylistic/semi-style":
    - "warn"
    - "last"
  "@stylistic/space-before-blocks":
    - "warn"
    - "always"
  "@stylistic/space-before-function-paren":
    - "warn"
    - anonymous: "always"
      named: "never"
      asyncArrow: "always"
  "@stylistic/space-in-parens":
    - "warn"
    - "never"
  "@stylistic/space-infix-ops":
    - "warn"
  "@stylistic/space-unary-ops":
    - "warn"
  "@stylistic/switch-colon-spacing":
    - "warn"
    - before: false
      after: true
  "@stylistic/template-curly-spacing":
    - "warn"
    - "never"
  "@stylistic/template-tag-spacing":
    - "warn"
    - "never"
  "@stylistic/wrap-iife":
    - "warn"
    - "any"
  "@stylistic/yield-star-spacing":
    - "warn"
    - before: false
      after: true
  "@typescript-eslint/adjacent-overload-signatures":
    - "warn"
  "@typescript-eslint/ban-ts-comment":
    - "warn"
    - ts-expect-error: "allow-with-description"
      ts-ignore: "allow-with-description"
      ts-nocheck: "allow-with-description"
      ts-check: "allow-with-description"
  "@typescript-eslint/ban-tslint-comment":
    - "warn"
  "@typescript-eslint/no-duplicate-enum-values":
    - "off"
