name: "Send Discord Webhook"
author: "hugoalh"
description: "Send a Discord webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to send."
    required: false
  payload:
    description: "{object} JSON/YAML payload."
    required: false
    default: "{}"
  files:
    description: "{string[]} Files as attachments of the message."
    required: false
    default: "[]"
  wait:
    description: "{boolean} Whether to wait for Discord confirmation of message send before response."
    required: false
    default: "false"
  thread_type:
    description: "{string} Thread type of the message; Send to the specified thread within a webhook's channel."
    required: false
    default: "none"
  thread_value:
    description: "{string} Thread value of the message."
    required: false
  truncate_enable:
    description: "{boolean} Whether to try truncate firstly when inputs are too large."
    required: false
    default: "true"
  truncate_ellipsis:
    description: "{string} Ellipsis mark."
    required: false
    default: "..."
  truncate_position:
    description: "{string} Ellipsis position."
    required: false
    default: "end"
  threadid:
    description: "{string} Thread ID of the message; Send to the specified thread within a webhook's channel."
    required: false
    deprecationMessage: "This input is replaced by `thread_type` and `thread_value`."
outputs:
  response:
    description: "{string} Response content."
  status_code:
    description: "{number} Request status code."
  status_ok:
    description: "{boolean} Whether the request was successful."
  status_text:
    description: "{string} Request status text."
runs:
  using: "node16"
  main: "dist/main.js"
branding:
  icon: "send"
  color: "blue"
