name: "Send To Discord"
author: "hugoalh"
description: "Send message to Discord via webhook, support variables."
inputs:
  webhook_id:
    description: "{string.secret} Discord webhook ID."
    required: true
  webhook_token:
    description: "{string.secret} Discord webhook token."
    required: true
  webhook_name:
    description: "{string} Webhook display name (i.e.: the sender's name)."
    required: false
  webhook_avatarurl:
    description: "{string} Webhook avatar url (i.e.: the sender's avatar)."
    required: false
  message_usetexttospeech:
    description: "{boolean} Use text to speech (TTS) for this message."
    required: false
    default: "false"
  message_text:
    description: "{string} Text."
    required: false
  message_embed_colour:
    description: "{string} Left border's colour of the embed."
    required: false
    default: "INVISIBLE"
  message_embed_authorname:
    description: "{string} Embed author name."
    required: false
  message_embed_authorurl:
    description: "{string} Embed author url."
    required: false
  message_embed_authoravatarurl:
    description: "{string} Embed author avatar url."
    required: false
  message_embed_title:
    description: "{string} Embed title."
    required: false
  message_embed_titleurl:
    description: "{string} Embed title url."
    required: false
  message_embed_description:
    description: "{string} Embed description."
    required: false
  message_embed_thumbnailurl:
    description: "{string} Embed thumbnail url."
    required: false
  message_embed_imageurl:
    description: "{string} Embed image url."
    required: false
  message_embed_videourl:
    description: "{string} Embed video url."
    required: false
  message_embed_field_0_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_0_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_0_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_1_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_1_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_1_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_2_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_2_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_2_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_3_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_3_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_3_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_4_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_4_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_4_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_5_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_5_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_5_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_6_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_6_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_6_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_7_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_7_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_7_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_8_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_8_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_8_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_9_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_9_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_9_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_10_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_10_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_10_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_11_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_11_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_11_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_12_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_12_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_12_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_13_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_13_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_13_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_14_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_14_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_14_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_15_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_15_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_15_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_16_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_16_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_16_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_17_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_17_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_17_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_18_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_18_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_18_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_19_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_19_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_19_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_20_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_20_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_20_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_21_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_21_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_21_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_22_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_22_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_22_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_23_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_23_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_23_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_field_24_key:
    description: "{string} Key for this embed field."
    required: false
  message_embed_field_24_value:
    description: "{string} Value for this embed field."
    required: false
  message_embed_field_24_isinline:
    description: "{boolean} Use inline for this embed field."
    required: false
    default: "false"
  message_embed_footericonurl:
    description: "{string} Embed footer icon url."
    required: false
  message_embed_footertext:
    description: "{string} Embed footer text."
    required: false
  variable_list_external:
    description: "{object.json} External variable list that will use in the data."
    required: false
  variable_prefix:
    description: "{string} Variable prefix."
    required: false
    default: "%"
  variable_suffix:
    description: "{string} Variable suffix."
    required: false
    default: "%"
  variable_join:
    description: "{string} Variable join if the variable list has depth."
    required: false
    default: "_"
runs:
  using: "node12"
  pre: "setup.js"
  main: "main.js"
branding:
  icon: "send"
  color: "blue"
