# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "錯誤報告"
description: "報告一個錯誤。"
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "描述"
      description: |-
        是甚麼錯誤？如果需要，附加圖片和／或影片以幫助解釋這個錯誤。
        
        > **ℹ️ 注意：**
        >
        > - 不應該模糊圖片和／或影片中的任何內容，個人資料除外。
        > - 對於上載圖片和／或影片，請確保等待上載過程完成。
        > - 對於外部圖片和／或影片，請確保我們是否可以檢閱它們。
    validations:
      required: true
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "重現"
      description: |-
        這個錯誤是否可以重現？如果可以重現，請通過列表、圖片和／或影片展示所需要的步驟！
        
        > **ℹ️ 注意：**
        >
        > - 不應該模糊圖片和／或影片中的任何內容，個人資料除外。
        > - 對於上載圖片和／或影片，請確保等待上載過程完成。
        > - 對於外部圖片和／或影片，請確保我們是否可以檢閱它們。
      placeholder: |-
        1. 前往＊＊＊＊。
        2. 點擊＊＊＊＊。
        3. 移動到＊＊＊＊。
        4. 遇到這個錯誤。
    validations:
      required: false
  - type: "textarea"
    id: "expected-behaviour"
    attributes:
      label: "預期行為"
      description: |-
        應該要發生甚麼事情？
    validations:
      required: false
  - type: "textarea"
    id: "version"
    attributes:
      label: "版本"
      description: |-
        甚麼版本受到這個錯誤影響？
        
        > **ℹ️ 注意：**
        >
        > - 接受版本範圍。
        > - 對於多個版本和／或版本範圍，使用 Markdown 無序列表語法列出。
        > - 必須是安全政策（檔案：`SECURITY-ZH.md`）中列出的受支持版本。
    validations:
      required: false
  - type: "textarea"
    id: "execution-environment"
    attributes:
      label: "執行環境"
      description: |-
        執行環境如何？

        - <b>裝置類型：</b>`電腦` / `手機` / `伺服器` / ...
        - <b>指令集架構：</b>`X64` / `X86` / `ARM64` / `ARM32` / `RISC` / ...
        - <b>平台：</b>`Windows 11 22H2` / `Android 14` / `Alpine 3.18.0` / `NodeJS 20.6.0` / `Deno 1.36.0` / `Git 2.42.0` / `Python 3.11.0` / ...
        - <b>是否在子系統中：</b>`否` / `是`
        - <b>變量：</b>`NO_COLOR=1` / ...

        > **ℹ️ 注意：**
        >
        > - 接受多個執行環境。
        > - 所有屬性都是選擇性的。
        > - 建議提供此資料以實現可重現的步驟。
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "額外資料"
      description: |-
        如果有與這個錯誤相關但是不適用於其他欄位的資料，請在此處列出。
    validations:
      required: false
