# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "錯誤報告"
description: "報告一個錯誤。"
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "描述"
      description: |-
        是甚麼錯誤？如果需要，附加圖片和／或影片以幫助解釋這個錯誤。

        > **ℹ️ 注意**
        >
        > - 不應該模糊圖片和／或影片中的任何內容，個人資料除外。
        > - 對於外部圖片和／或影片，請確保我們能夠檢閱它們。
      placeholder: |-
        它不能＊＊＊＊＊＊＊＊。
    validations:
      required: true
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "重現"
      description: |-
        這個錯誤是否可以重現？如果可以重現，請通過列表、圖片和／或影片展示所需要的步驟！

        > **ℹ️ 注意**
        >
        > - 不應該模糊圖片和／或影片中的任何內容，個人資料除外。
        > - 對於外部圖片和／或影片，請確保我們能夠檢閱它們。
      placeholder: |-
        1. 前往＊＊＊＊＊＊＊＊。
        2. 點擊＊＊＊＊＊＊＊＊。
        3. 移動到＊＊＊＊＊＊＊＊。
        4. 遇到這個錯誤。
    validations:
      required: false
  - type: "textarea"
    id: "expected-behaviour"
    attributes:
      label: "預期行為"
      description: |-
        應該要發生甚麼事情？
      placeholder: |-
        它應該要＊＊＊＊＊＊＊＊。
    validations:
      required: false
  - type: "textarea"
    id: "version"
    attributes:
      label: "版本"
      description: |-
        甚麼版本受到這個錯誤影響？

        > **ℹ️ 注意**
        >
        > - 接受版本範圍。
        > - 必須是安全政策（英文，檔案 `SECURITY.md`）中列出的受支持版本。
      placeholder: |-
        1.2.3
    validations:
      required: false
  - type: "textarea"
    id: "execution-environment"
    attributes:
      label: "執行環境"
      description: |-
        執行環境如何？

        - **Type:** 裝置類型。
          > Computer / Phone / Server / ...
        - **Hardware:** 硬件規格。
        - **Platforms:** 操作系統和軟件，包括架構和版本。
          > Windows 11 22H2 X64 / Android 14 ARM64 / Alpine 3.18.0 X64 / NodeJS 20.6.0 X64 / Deno 1.36.0 X64 / Git 2.42.0 X64 / Python 3.11.0 X64 / ...
        - **IsSubSystem:** 執行環境是否在子系統中？
          > False / True
        - **Variables:** 環境變量。
          > NO_COLOR=1 / ...

        > **ℹ️ 注意**
        >
        > - 必須以 ASCII 字元填寫此欄位。
        > - 接受多個執行環境。
        > - 所有屬性都是選擇性的。
        > - 建議提供此資料以實現可重現的步驟。

        **\[🖌️ YAML\]**
      placeholder: |-
        - Type: Server
          Platforms:
            - Ubuntu 23.04 X64
            - NodeJS 20.6.0 X64
          IsSubSystem: false
      render: "yml"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "額外資料"
      description: |-
        如果有與這個錯誤相關但是不適用於其他欄位的資料，請在此處列出。
    validations:
      required: false
