# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Bug Report"
description: "Report a bug."
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "input"
    id: "version"
    attributes:
      label: "Version"
      description: |-
        Which version occur this bug? Version must be supported at the time of submit, the supported versions are listed in the Security Policy file `SECURITY.md`.

        > [!NOTE]
        > - For multiple versions, separate each version with comma-space (`, `), or use versions range syntax from [OSGi](https://docs.osgi.org/whitepaper/semantic-versioning/040-semantic-versions.html) or [SemVer](https://devhints.io/semver).
      placeholder: "1.0.2"
    validations:
      required: true
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: |-
        What the bug is? If needed, use images, videos, or other media type to help for explain this bug.

        > [!NOTE]
        > - For external media, please ensure we are able to view those without any extra step.
      placeholder: |-
        It unable to XXXXXXXX.
    validations:
      required: true
  - type: "input"
    id: "behaviour-expected"
    attributes:
      label: "Behaviour Expected"
      description: |-
        What things should expected to happen?
      placeholder: |-
        It should XXXXXXXX.
    validations:
      required: false
  - type: "input"
    id: "behaviour-actual"
    attributes:
      label: "Behaviour Actual"
      description: |-
        What things happened instead of the expected?
      placeholder: |-
        It XXXXXXXX.
    validations:
      required: false
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: |-
        Is this bug reproducible? If reproducible, please show the reproduce steps; If needed, use images, videos, or other media to help for show the reproduce steps.

        > [!NOTE]
        > - For external media, please ensure we are able to view those without any extra step.
      placeholder: |-
        1. Go to XXXXXXXX.
        2. Click on XXXXXXXX.
        3. Scroll to XXXXXXXX.
        4. Encounter this bug.
    validations:
      required: false
  - type: "dropdown"
    id: "frequency"
    attributes:
      label: "Frequency"
      description: |-
        How often does this bug occur?
      options:
        - "Unknown / Untested"
        - "Always (~100%)"
        - "Frequently (~75%)"
        - "Half (~50%)"
        - "Sometimes (~25%)"
        - "Rarely (~5%)"
      multiple: false
      default: 0
    validations:
      required: true
  - type: "textarea"
    id: "execution-environment"
    attributes:
      label: "Execution Environment"
      description: |-
        How is the execution environment? Different execution environment may have different outcome, provide this information may help for reproduce this bug.

        These are common categories:

        - **`type`:** Device type (e.g.: `computer`, `phone`, `server`).
        - **`cpu`:** Details of the central processing unit (e.g.: `Intel i7-6700`).
        - **`ram`:** Details of the random access memory (e.g.: `8 GB`).
        - **`storage`:** Details of the storage unit (e.g.: `500 GB SSD`).
        - **`network`:** Details of the network.
        - **`gpu`:** Details of the graphics processing unit (e.g.: `NVIDIA GeForce RTX 4090`).
        - **`os`:** Details of the operate system (e.g.: `Windows 11 Professional 23H2 X64`).
        - **`softwares`:** List of the installed softwares (e.g.: `NodeJS 20.6.0 X64`, `Deno 1.36.0 X64`).
        - **`env`:** List of the environment variables (e.g.: `NO_COLOR=1`).

        > [!NOTE]
        > - Accept multiple execution environments.
        > - All of the categories are optional.

        **\[🖌️ YAML\]**
      render: "yml"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |-
        If there have information which relevant to this bug but not suitable at other fields, please list those at here.
    validations:
      required: false
