# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Bug Report"
description: "Report a bug."
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: |-
        What the bug is? Add images and/or videos to help for explain this bug if needed.

        > **ℹ️ Notice:**
        >
        > - Should not blur anything in the images and/or videos, except personal secrets.
        > - For external images and/or videos, please ensure we are able to view those.
      placeholder: |-
        It cannot XXXXXXXX.
    validations:
      required: true
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: |-
        Is this bug reproducible? If reproducible, please show the required steps by list, images, and/or videos!

        > **ℹ️ Notice:**
        >
        > - Should not blur anything in the images and/or videos, except personal secrets.
        > - For external images and/or videos, please ensure we are able to view those.
      placeholder: |-
        1. Go to XXXXXXXX.
        2. Click on XXXXXXXX.
        3. Scroll to XXXXXXXX.
        4. Encounter this error.
    validations:
      required: false
  - type: "textarea"
    id: "expected-behaviour"
    attributes:
      label: "Expected Behaviour"
      description: |-
        What things should expected to happen?
      placeholder: |-
        It should XXXXXXXX.
    validations:
      required: false
  - type: "textarea"
    id: "version"
    attributes:
      label: "Version"
      description: |-
        Which versions are affected by this bug?

        > **ℹ️ Notice:**
        >
        > - Accept versions range.
        > - Versions must be listed as supported in the Security Policy (file: `SECURITY.md`).
      placeholder: |-
        1.2.3
    validations:
      required: false
  - type: "textarea"
    id: "execution-environment"
    attributes:
      label: "Execution Environment"
      description: |-
        How is the execution environment?

        - **Type:** Device type.
          > Computer / Phone / Server / ...
        - **Hardware:** Hardware specifications.
        - **Platforms:** Operate system and softwares, with architecture and version.
          > Windows 11 22H2 X64 / Android 14 ARM64 / Alpine 3.18.0 X64 / NodeJS 20.6.0 X64 / Deno 1.36.0 X64 / Git 2.42.0 X64 / Python 3.11.0 X64 / ...
        - **IsSubSystem:** Whether the execution environment in the sub system?
          > False / True
        - **Variables:** Environment variables.
          > NO_COLOR=1 / ...

        > **ℹ️ Notice:**
        >
        > - Accept multiple execution environments.
        > - All of the properties are optional.
        > - It is recommended to provide this information for reproducible steps.

        **\[🖌️ YAML\]**
      placeholder: |-
        - Type: Server
          Platforms:
            - Ubuntu 23.04 X64
            - NodeJS 20.6.0 X64
          IsSubSystem: false
      render: "yml"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |-
        If there have information that related to this bug but not suitable at other fields, please list those at here.
    validations:
      required: false
