# ==================
# hugoalh's Repository Resource - GitHub Issues Configuration
#   Language:
#     YAML
#   Last Update:
#     2020-07-25
#   Schema:
#     https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
# ==================
blank_issues_enabled: true
