# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Feature Request"
description: "Suggest an idea."
labels:
  - "Status/Pending 🔵"
  - "Type/Enhancement 💡"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: "What feature do you want?"
    validations:
      required: false
  - type: "textarea"
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "What things should expected to happen?"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: "If there have information that related to this issue but not suitable to the other fields, please list those at here."
    validations:
      required: false
