# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Feature Request"
description: "Suggest an idea."
labels:
  - "Status/Pending 🔵"
  - "Type/Enhancement 💡"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: |-
        What feature do you want? Is your feature request related to a problem? If needed, use images, videos, or other media type to help for explain this feature.

        > [!NOTE]
        > - For external media, please ensure we are able to view those without any extra step.
    validations:
      required: true
  - type: "input"
    id: "behaviour-expected"
    attributes:
      label: "Behaviour Expected"
      description: |-
        What things should expected to happen?
      placeholder: |-
        It should XXXXXXXX.
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |-
        If there have information which relevant to this feature but not suitable at other fields, please list those at here.
    validations:
      required: false
