# $<Schema>$ https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Send Discord Webhook"
author: "hugoalh"
description: "Send a Discord webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to send."
    required: false
  payload:
    description: "{object} JSON payload."
    required: false
    default: "{}"
  files:
    description: "{string[]} Files as attachment."
    required: false
    default: "[]"
  threadid:
    description: "{string} Thread ID; Send to the specified thread within a webhook's channel."
    required: false
  wait:
    description: "{boolean} Wait for Discord confirmation of message send before response."
    required: false
    default: "false"
  truncate_enable:
    description: "{boolean} When input `payload` is too large, try to prune/trim/truncate first."
    required: false
    default: "true"
  truncate_ellipsis:
    description: "{string} Ellipsis."
    required: false
    default: "..."
  truncate_position:
    description: "{string} Ellipsis position."
    required: false
    default: "end"
  dryrun:
    description: "{boolean} Dry run."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "send"
  color: "blue"
