name: "Send Discord Webhook"
author: "hugoalh"
description: "Send Discord webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  username:
    description: "{string} Override the default webhook username."
    required: false
  avatar_url:
    description: "{string} Override the default webhook avatar."
    required: false
  content:
    description: "{string} Message content."
    required: false
  content_links_no_embed:
    description: "{RegExp[]} Links' regular expressions to prevent Discord resolve and display matches links in the content as embed under the message."
    required: false
  embeds:
    description: "{object[]} Message embed rich content."
    required: false
  poll_question:
    description: "{string} Message poll question."
    required: false
  poll_answers:
    description: "{object[]} Message poll answers."
    required: false
  poll_duration:
    description: "{number} Message poll duration."
    required: false
  poll_allow_multiselect:
    description: "{boolean} Whether the message poll allow multiple select answers."
    required: false
  files:
    description: "{string[]} Message files as attachments."
    required: false
  allowed_mentions_parse:
    description: "{string[]} Allowed mention types to parse from the message."
    required: false
  allowed_mentions_roles:
    description: "{string[]} Allowed roles' IDs to mention in the message."
    required: false
  allowed_mentions_users:
    description: "{string[]} Allowed users' IDs to mention in the message."
    required: false
  tts:
    description: "{boolean} Whether to use TTS (Text To Speech) for the message."
    required: false
  thread_id:
    description: "{string} Thread ID for the message channel."
    required: false
  thread_name:
    description: "{string} Thread name for the forum channel."
    required: false
  thread_tags:
    description: "{string[]} Thread tags ID for the forum channel."
    required: false
  truncate_enable:
    description: "{boolean} Whether to try truncate firstly when inputs are too large."
    required: false
  truncate_ellipsis:
    description: "{string} Ellipsis mark."
    required: false
  truncate_position:
    description: "{string} Ellipsis position."
    required: false
  wait:
    description: "{boolean} Whether to wait for Discord confirmation of message send before response."
    required: false
outputs:
  response:
    description: "{string} Response content."
  status_code:
    description: "{number} Request status code."
  status_ok:
    description: "{boolean} Whether the request was successful."
  status_text:
    description: "{string} Request status text."
runs:
  using: "docker"
  image: "../Dockerfile"
branding:
  icon: "send"
  color: "blue"
