# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Analyze Code - GitHub Super Linter"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
jobs:
  analyze-code-ghsl:
    name: "Analyze Code - GitHub Super Linter"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.1"
        with:
          fetch-depth: 0
      - name: "Analyze Repository"
        uses: "github/super-linter@v4.9.2"
        env:
          DISABLE_ERRORS: "true"
          GITHUB_TOKEN: "${{github.token}}"
