# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Announce New Release"
on:
  release:
    types:
      - "published"
jobs:
  discord:
    name: "Discord"
    permissions: {}
    runs-on: "ubuntu-latest"
    steps:
      - name: "Send Discord Webhook"
        uses: "hugoalh/send-discord-webhook-ghaction@main"
        with:
          key: "${{secrets.DISCORD_HXHS_PROJECTNEWRELEASEANNOUNCER_WEBHOOK}}"
          embeds: |
            - title: "Send Discord Webhook (GitHub Action)"
              description: |
                > ${{github.event.repository.description}}

                Version ${{github.event.release.name}} (`${{github.event.release.tag_name}}`) just released!
              timestamp: "${{github.event.release.published_at}}"
              color: "#2088FF"
              author:
                name: "${{github.event.release.author.login}}"
                url: "${{github.event.release.author.html_url}}"
                icon_url: "${{github.event.release.author.avatar_url}}"
              fields:
                - name: "📋 Changelog"
                  value: "${{github.event.release.html_url}}"
                  inline: false
                - name: "GitHub"
                  value: "${{github.event.repository.html_url}}"
                  inline: false
